name: deploy-staging-on-merge
run-name: ${{ github.actor }} is deploying to staging env.
on: [workflow_dispatch]
jobs:
  staging_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@master
      - name: Install dependencies and build project
        run: |
          npm install
          npm run build
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          ARGS: >-
            --exclude='.git'
            --exclude='src/'
            --exclude='node_modules/'
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.STAGING_DEPLOY_PATH }}
