name: deploy-staging-on-merge
run-name: ${{ github.actor }} is deploying to staging env.
on:
  pull_request:
    branches: [staging]
    types: [closed]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3
        uses: actions/setup-node@master
      - name: Install dependencies and build project
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_STAGING }}
          ARGS: >-
            --exclude='.git'
            --exclude='src/'
            --exclude='node_modules/'
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: ${{ secrets.STAGING_DEPLOY_PATH }}
